/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as RootRouteImport } from './routes/_root/route'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as RootIndexImport } from './routes/_root/index'
import { Route as RootProfileImport } from './routes/_root/profile'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const RootRouteRoute = RootRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const RootIndexRoute = RootIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootProfileRoute = RootProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RootRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_root/profile': {
      id: '/_root/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof RootProfileImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/': {
      id: '/_root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface RootRouteRouteChildren {
  RootProfileRoute: typeof RootProfileRoute
  RootIndexRoute: typeof RootIndexRoute
}

const RootRouteRouteChildren: RootRouteRouteChildren = {
  RootProfileRoute: RootProfileRoute,
  RootIndexRoute: RootIndexRoute,
}

const RootRouteRouteWithChildren = RootRouteRoute._addFileChildren(
  RootRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof RootRouteRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/profile': typeof RootProfileRoute
  '/': typeof RootIndexRoute
  '/login': typeof LoginIndexRoute
}

export interface FileRoutesByTo {
  '/sign-up': typeof SignUpRoute
  '/profile': typeof RootProfileRoute
  '/': typeof RootIndexRoute
  '/login': typeof LoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_root': typeof RootRouteRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/_root/profile': typeof RootProfileRoute
  '/_root/': typeof RootIndexRoute
  '/login/': typeof LoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/sign-up' | '/profile' | '/' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-up' | '/profile' | '/' | '/login'
  id:
    | '__root__'
    | '/_root'
    | '/sign-up'
    | '/_root/profile'
    | '/_root/'
    | '/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RootRouteRoute: typeof RootRouteRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  RootRouteRoute: RootRouteRouteWithChildren,
  SignUpRoute: SignUpRoute,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_root",
        "/sign-up",
        "/login/"
      ]
    },
    "/_root": {
      "filePath": "_root/route.tsx",
      "children": [
        "/_root/profile",
        "/_root/"
      ]
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/_root/profile": {
      "filePath": "_root/profile.tsx",
      "parent": "/_root"
    },
    "/_root/": {
      "filePath": "_root/index.tsx",
      "parent": "/_root"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
